### PR TITLE
Rsa keys algs

### LINKED ISSUE #33: Adding RSA keys and algorithms
I really appreciate all of the effort that's gone into this library. For my purposes I want to produce some examples using RSA keypairs, and I'm comfortable hammering in an `RSA` key class in a local fork then later making a merge request.

This ticket is really to note the missing behavior and make sure there's no parallel effort.

### PR DESCRIPTION
**Pull request by BSipos-RKF**
This MR uses the new `CoseKey` behavior. This would close #33.

It still has an `RSAKey.is_valid_key()` which was taken out of the others.

### CODE REVIEW

**Comment by mpzaborski** [comment]
Hello! Good job! What is a status of this PR? I needed RsaesOaepSha256 in my usecase and it works well.

**Comment by BSipos-RKF** [comment]
There are no unit tests for the PKCS#1 algorithms, but those are also not recommended. Loopback tests (sign-then-verify or encrypt-then-decrypt) could be added quite easily if needed. This could also be done after merging, depending on what kind of test coverage is desired.

**Comment by TimothyClaeys** [comment]
I've done a rebase of this branch on `master` locally and I'm going through the code. I'm might look at adding some tests here and there. I'll merge when I've been over all the code.

**Comment by TimothyClaeys** [comment]
I've integrated all the commits in the [develop](https://github.com/TimothyClaeys/pycose/tree/develop) branch. I've updated the code so it is consistent with the rest of the library. Let me know if you have any remarks and then I'll merge into `master`

**Comment by BSipos-RKF** [comment]
Your edits look good. My PR was just a starting point for algorithmic behavior.

**Pull request closed without merging**
